version: "3"
services:
  hmpps-adjudications-insights-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-adjudications-insights-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - 8999:8080
      - 9080:9080
    environment:
      - SERVICES=s3
      - PORT_WEB_UI=9080
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./localstack:/tmp/localstack"
#      - /src/test/resources/test-data/1a.json:/tmp/localstack/aaa
      - "$PWD/src/test/resources/localstack/setup-s3.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
