# Localstack settings
aws:
  sqs-endpoint-url: "http://localhost:4566"
  region-name: eu-west-2
  access_key: foobar
  secret_access_key: foobar
  s3:
    access_key: foobar
    secret_access_key: foobar
    access_key_id: foobar
    bucket_name: mojap-adjudications-insights


