---
# Per environment values which override defaults in hmpps-adjudications-insights-api/values.yaml

generic-service:
  replicaCount: 2
  serviceAccountName: hmpps-manage-adjudications-api-preprod-analytical-platform

  ingress:
    host: adjudications-insights-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    S3_REGION: "eu-west-1"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
